version: "3.7"

services: 
  mass-js:
    container_name: mass-js
    user: node
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: 
      - traefik_default
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - traefik.enable=true
      - traefik.http.services.mass-js.loadbalancer.server.port=443
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

networks:
  traefik_default:
    external: true